### ISSUE TITLE
i like your package, could you continue to develop it ?

### ISSUE THREAD

**Issue by nicodmf** [mjaneczek/conventional-redux#1]

**Comment by mjaneczek** [comment]
I'm planning the new version with some major changes, e.g add function style for components (only html in the component and the rest in the interactor) but I cannot promise any date.

I'm working on my private project using conventional-redux and try to fit the library for my needs, so basically I'm planning to release an update for the library and open source project which uses it as an example.

Thanks for the issue, it's awesome that you like it, please feel free to write any comments and ideas of improvement.

**Comment by iamsoorena** [comment]
it's really great and solves a lot of problems. thanks for your efforts.

**Comment by mjaneczek** [comment]
The new version has been released. Feel free to comment. 😄
